---

kms_plan:
  stage: KMS
  needs: []
  resource_group: kms
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-kms
    TF_ROOT: kms
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  environment:
    name: ${ENVIRONMENT}-plan
  artifacts:
    name: plan
    paths:
      - kms/plan.cache
    reports:
      terraform: kms/plan.json
  when: manual

kms_apply:
  stage: KMS
  resource_group: kms
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-kms
    TF_ROOT: ${CI_PROJECT_DIR}/kms
  environment:
    name: ${ENVIRONMENT}-apply
  script:
    - gitlab-terraform apply
  needs:
    - job: kms_plan
      artifacts: true
  when: manual
