---

instances_plan:
  stage: Instances
  needs: []
  resource_group: ec2_instance
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-ec2_instance
    TF_ROOT: ec2_instance
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  environment:
    name: ${ENVIRONMENT}-plan
  artifacts:
    name: plan
    paths:
      - ec2_instance/plan.cache
    reports:
      terraform: ec2_instance/plan.json
  when: manual

instances_apply:
  stage: Instances
  resource_group: ec2_instance
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-ec2_instance
    TF_ROOT: ${CI_PROJECT_DIR}/ec2_instance
  environment:
    name: ${ENVIRONMENT}-apply
  script:
    - gitlab-terraform apply
  needs:
    - job: instances_plan
      artifacts: true
  when: manual
