---

efs_plan:
  stage: EFS
  needs: []
  resource_group: efs
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-efs
    TF_ROOT: efs
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  environment:
    name: ${ENVIRONMENT}-plan
  artifacts:
    name: plan
    paths:
      - efs/plan.cache
    reports:
      terraform: efs/plan.json
  when: manual

efs_apply:
  stage: EFS
  resource_group: efs
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-efs
    TF_ROOT: ${CI_PROJECT_DIR}/efs
  environment:
    name: ${ENVIRONMENT}-apply
  script:
    - gitlab-terraform apply
  needs:
    - job: efs_plan
      artifacts: true
  when: manual
