---

security_group_plan:
  stage: SecurityGroups
  needs: []
  resource_group: security_group
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-security_group
    TF_ROOT: security_group
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  environment:
    name: ${ENVIRONMENT}-plan
  artifacts:
    name: plan
    paths:
      - security_group/plan.cache
    reports:
      terraform: security_group/plan.json
  when: manual

security_group_apply:
  stage: SecurityGroups
  resource_group: security_group
  variables:
    TF_STATE_NAME: ${ENVIRONMENT}-security_group
    TF_ROOT: ${CI_PROJECT_DIR}/security_group
  environment:
    name: ${ENVIRONMENT}-apply
  script:
    - gitlab-terraform apply
  needs:
    - job: security_group_plan
      artifacts: true
  when: manual
